namespace Planner.Common.Enums
{
	public enum CleaningProcessStatus
	{
		/// <summary>
		/// While the cleaning plan is not sent yet. Once the plan is sent, the cleaning can't have the DRAFT status any more.
		/// </summary>
		DRAFT = 0,

		/// <summary>
		/// After the cleaning plan is created and sent, the cleaning status is set to NEW.
		/// </summary>
		NEW = 1,

		/// <summary>
		/// After the cleaning is received and seen by the cleaner.
		/// </summary>
		SEEN_NEW,

		/// <summary>
		/// Once the cleaner starts the cleaning
		/// </summary>
		IN_PROGRESS,

		/// <summary>
		/// If the cleaning is paused for some reason
		/// </summary>
		PAUSED,

		/// <summary>
		/// If the cleaning is fully finished and the inspection is not required.
		/// </summary>
		FINISHED,

		/// <summary>
		/// If the cleaning is finished and the inspection is required.
		/// </summary>
		REQUIRES_INSPECTION,

		INSPECTION_STARTED,

		/// <summary>
		/// If the cleaning ispection finished successfully.
		/// </summary>
		INSPECTION_FINISHED,

		/// <summary>
		/// If the inspection failed and the cleaning must be redone so there is a *new* cleaning.
		/// </summary>
		INSPECTION_FAILED,

		/// <summary>
		/// The user has seen the new cleaning generated by the failed inspection.
		/// </summary>
		SEEN_INSPECTION_FAILED,

		/// <summary>
		/// The cleaning was cancelled by the cleaner.
		/// </summary>
		CLEANING_CANCELLED_BY_CLEANER,

		/// <summary>
		/// The cleaning was cancelled by the administrator.
		/// </summary>
		CLEANING_CANCELLED_BY_ADMIN,

		/// <summary>
		/// The cleaning was cancelled by the system - some automatic service or something.
		/// </summary>
		CLEANING_CANCELLED_BY_SYSTEM,

		UNKNOWN,


		/// <summary>
		/// If the room is do not disturb
		/// </summary>
		DO_NOT_DISTURB,

		/// <summary>
		/// If the cleaning was delayed by the guest?
		/// </summary>
		DELAYED,
		/// <summary>
		/// If the cleaning was refused by the guest?
		/// </summary>
		REFUSED,
	}


}
