namespace Planner.Common.Enums
{
	public enum WarehouseDocumentType
	{
		RECEIPT_MANUAL_INIT,
		RECEIPT_MOVE_WAREHOUSE,
		DISPATCH_MANUAL,
		DISPATCH_MOVE_WAREHOUSE,
	}

	public enum UserEventType
	{
		LOGGED_IN,
		LOGGED_OUT,
		CAME_ON_DUTY,
		CAME_OFF_DUTY,
		CLEANING_STARTED,
		CLEANING_PAUSED,
		CLEANING_UNPAUSED,
		CLEANING_RESTARTED,
		CLEANING_FINISHED,

		CLEANING_INSPECTION_FINISHED,
		CLEANING_REFUSED,
		CLEANING_DO_NOT_DISTURB,
		CLEANING_DELAYED,

		REGISTERED_GUEST_ENTERED_ROOM,
		REGISTERED_GUEST_LEFT_ROOM,

		CLEANING_INSPECTION_DO_NOT_DISTURB,
		CLEANING_INSPECTION_REQUIRES_INSPECTION,
		CLEANING_INSPECTION_CLEANING_IN_PROGRESS,
		CLEANING_INSPECTION_NEW_CLEANING,
		CLEANING_INSPECTION_CHANGED,
		
		CLEANING_NEW,

		ROOM_CLEANING_PRIORITY_ENABLED,
		ROOM_CLEANING_PRIORITY_DISABLED,
	}
	public enum RoomEventType
	{
		CREATED_BY_USER,
		CREATED_BY_RCC_SYNC,
		CREATED_BY_SYSTEM,
		UPDATED_BY_USER,
		UPDATED_BY_SYSTEM,

		CLEANING_CREATED,
		CLEANING_STARTED,
		CLEANING_PAUSED,
		CLEANING_UNPAUSED,
		CLEANING_RESTARTED,
		CLEANING_FINISHED,
		CLEANING_FINISHED_READY_FOR_INSPECTION,
		CLEANING_CANCELLED_BY_CLEANER,
		CLEANING_CANCELLED_BY_ADMIN,
		CLEANING_CANCELLED_BY_SYSTEM,

		CLEANING_INSPECTION_STARTED,
		CLEANING_INSPECTION_PAUSED,
		CLEANING_INSPECTION_FINISHED,
		CLEANING_INSPECTION_CANCELLED_BY_INSPECTOR,
		CLEANING_INSPECTION_CANCELLED_BY_ADMIN,
		CLEANING_INSPECTION_CANCELLED_BY_SYSTEM,

		CLEANING_INSPECTION_DO_NOT_DISTURB,
		CLEANING_INSPECTION_REQUIRES_INSPECTION,
		CLEANING_INSPECTION_CLEANING_IN_PROGRESS,
		CLEANING_INSPECTION_NEW_CLEANING,
		CLEANING_INSPECTION_CHANGED,

		CLEANING_REFUSED,
		CLEANING_DO_NOT_DISTURB,
		CLEANING_DELAYED,

		MAINTENANCE_STARTED,
		MAINTENANCE_PAUSED,
		MAINTENANCE_FINISHED,
		MAINTENANCE_CANCELLED_BY_INSPECTOR,
		MAINTENANCE_CANCELLED_BY_ADMIN,
		MAINTENANCE_CANCELLED_BY_SYSTEM,

		GUEST_CHECKED_IN,
		GUEST_CHECKED_OUT,

		GUEST_ENTERED_ROOM,
		GUEST_LEFT_ROOM,

		CLEANING_NEW,

		CLEANING_PRIORITY_ENABLED,
		CLEANING_PRIORITY_DISABLED,

		PMS_EVENT,

		RCCSYNC_GUEST_ENTERED_ROOM,
		RCCSYNC_GUEST_LEFT_ROOM,
		RCCSYNC_ROOM_IS_OCCUPIED,
		RCCSYNC_ROOM_IS_VACANT,
		RCCSYNC_RCC_HK_STATUS_CHANGED,
		RCCSYNC_RCC_ROOM_STATUS_CHANGED,
		RCCSYNC_ROOM_EXTERNAL_ID_CHANGED,
		RCCSYNC_BED_EXTERNAL_ID_CHANGED,
		RCCSYNC_ROOM_CREATED,
		RCCSYNC_BED_CREATED,
		RCCSYNC_RCC_ROOM_BED_STATUS_CHANGED,
		RCCSYNC_ROOM_OUT_OF_SERVICE,
		RCCSYNC_ROOM_IN_SERVICE,


	}
	public enum CleaningEventType
	{
		CREATED,
		SENT_TO_CLIENT,
		CANCELLED,
		UPDATED,

		SEEN_BY_CLEANER,
		STARTED,
		PAUSED,
		FINISHED,
		RESTARTED,
		UNPAUSED,

		INSPECTION_FINISHED,
		INSPECTION_DO_NOT_DISTURB,
		INSPECTION_REQUIRES_INSPECTION,
		INSPECTION_CLEANING_IN_PROGRESS,
		INSPECTION_NEW_CLEANING,
		INSPECTION_CHANGED,

		REFUSED,
		DO_NOT_DISTURB,
		DELAYED,

		NEW,
	}
}
