import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, FormArray, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { LoadingService } from '../core/services/loading.service';
import { ToastrService } from 'ngx-toastr';
import { HotelService } from '../core/services/hotel.service';
import { BehaviorSubject } from 'rxjs';
import { GetPageOfLostAndFoundCategoriesQuery, GetLostAndFoundCategoryDetailsQuery, InsertLostAndFoundCategoryCommand, PageOfOfLostAndFoundCategoryGridItemViewModel, ProcessResponse, ProcessResponseOfGuid, LostAndFoundCategoryDetailsViewModel, LostAndFoundCategoryGridItemViewModel, LostAndFoundCategoryManagementClient, UpdateLostAndFoundCategoryCommand } from '../core/autogenerated-clients/api-client';
import { debounceTime } from 'rxjs/operators';

@Component({
  selector: 'app-lost-and-found-categories-management',
  templateUrl: './lost-and-found-categories-management.component.html',
  styleUrls: ['./lost-and-found-categories-management.component.scss']
})
export class LostAndFoundCategoriesManagementComponent implements OnInit {
  sorts = [
    { key: 'NAME_ASC', value: 'Name A to Z' },
    { key: 'NAME_DESC', value: 'Name Z to A' },
    { key: 'CREATED_AT_DESC', value: 'Newest first' },
    { key: 'CREATED_AT_ASC', value: 'Oldest first' },
    { key: 'EXPIRATION_DAYS_ASC', value: 'Expiration days High to Low' },
    { key: 'EXPIRATION_DAYS_DESC', value: 'Expiration days Low to High' },
  ];

  isCategoryLoaded$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
  isLoadingCategoryDetails$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
  showLoadMore$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
  loadedNumberOfCategories$: BehaviorSubject<number> = new BehaviorSubject<number>(0);
  totalNumberOfCategories$: BehaviorSubject<number> = new BehaviorSubject<number>(0);
  selectedCategoryId$: BehaviorSubject<string> = new BehaviorSubject<string>(null);
  Categories$: BehaviorSubject<LostAndFoundCategoryGridItemViewModel[]> = new BehaviorSubject<LostAndFoundCategoryGridItemViewModel[]>([]);


  areDetailsDisplayed$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);

  selectedCategoryDetails$: BehaviorSubject<LostAndFoundCategoryDetailsViewModel> = new BehaviorSubject<LostAndFoundCategoryDetailsViewModel>(new LostAndFoundCategoryDetailsViewModel({
    id: null,
    name: null,
    expirationDays: 0
  }));

  filterForm: FormGroup;

  constructor(
    public loading: LoadingService,
    private _formBuilder: FormBuilder,
    private _CategoryManagementClient: LostAndFoundCategoryManagementClient,
    private _route: ActivatedRoute,
    private _toastr: ToastrService) {
  }

  ngOnInit(): void {
    this.loading.start();

    this.filterForm = this._formBuilder.group({
      sortKey: ['NAME_ASC'],
      keywords: [''],
    });

    this.filterForm.valueChanges.pipe(
      debounceTime(300)
    ).subscribe(
      (formValues: any) => { this._loadCategories(0); },
      (error: Error) => { },
      () => { }
    );

    this._loadCategories(0);
  }

  selectCategory(category: LostAndFoundCategoryGridItemViewModel) {
    this.isLoadingCategoryDetails$.next(true);
    this.selectedCategoryId$.next(category.id);
    this.loading.start();
    let request = new GetLostAndFoundCategoryDetailsQuery({ id: category.id });

    this._CategoryManagementClient.getLostAndFoundCategoryDetails(request).subscribe(
      (categoryDetails: LostAndFoundCategoryDetailsViewModel) => {
        this.selectedCategoryDetails$.next(categoryDetails);
        this.isCategoryLoaded$.next(true);
        this.areDetailsDisplayed$.next(true);
      },
      (error: Error) => {
        this._toastr.error(error.message);
      },
      () => {
        this.isLoadingCategoryDetails$.next(false);
        this.loading.stop();
      }
    );
  }

  loadMoreCategories() {
    this._loadCategories(this.loadedNumberOfCategories$.value);
  }

  newCategoryDetails() {
    this.selectedCategoryId$.next(null);
    this.selectedCategoryDetails$.next(this._createNewCategoryDetails());
    this.isCategoryLoaded$.next(true);

    this.areDetailsDisplayed$.next(true);
  }

  onCategoryInserted(category: LostAndFoundCategoryDetailsViewModel) {
    this.selectedCategoryDetails$.next(category);
    this.selectedCategoryId$.next(category.id);
    this.Categories$.next([...this.Categories$.value, new LostAndFoundCategoryGridItemViewModel(category)]);
    this.loadedNumberOfCategories$.next(this.loadedNumberOfCategories$.value + 1);
    this.totalNumberOfCategories$.next(this.totalNumberOfCategories$.value + 1);
  }

  onCategoryUpdated(category: LostAndFoundCategoryDetailsViewModel) {
    this.selectedCategoryDetails$.next(category);

    let Categories = [...this.Categories$.value];
    let categoryItem = Categories.find(c => c.id === category.id);
    if (categoryItem) {
      categoryItem.name = category.name;
      categoryItem.expirationDays = category.expirationDays;
      this.Categories$.next(Categories);
    }
  }

  onCategoryCancel() {
    this.areDetailsDisplayed$.next(false);
    this.selectedCategoryId$.next(null);
  }

  private _createNewCategoryDetails(): LostAndFoundCategoryDetailsViewModel {
    return new LostAndFoundCategoryDetailsViewModel({
      id: null,
      name: null,
      expirationDays: 0
    });
  }

  private _loadCategories(skip: number) {
    this.loading.start();

    let query: GetPageOfLostAndFoundCategoriesQuery = new GetPageOfLostAndFoundCategoriesQuery({
      skip: skip,
      take: 20,
      keywords: this.filterForm.controls.keywords.value,
      sortKey: this.filterForm.controls.sortKey.value
    });

    this._CategoryManagementClient.getPageOfLostAndFoundCategories(query).subscribe(
      (response: PageOfOfLostAndFoundCategoryGridItemViewModel) => {
        if (skip === 0) {
          this.Categories$.next(response.items);
        } else {
          this.Categories$.next([...this.Categories$.value, ...response.items]);
        }
        this.totalNumberOfCategories$.next(response.totalNumberOfItems);
        this.loadedNumberOfCategories$.next(this.Categories$.value.length);
        this.showLoadMore$.next(this.loadedNumberOfCategories$.value < this.totalNumberOfCategories$.value);
      },
      (error: Error) => {
        this._toastr.error(error.message);
      },
      () => {
        this.loading.stop();
      },
    );
  }
}
