import { Injectable } from "@angular/core";
import { ActivatedRouteSnapshot, Resolve } from "@angular/router";
import { Observable } from "rxjs";
import { map } from 'rxjs/operators';
import { GetPageOfCategoriesQuery, PageOfOfCategoryGridItemViewModel, CategoryGridItemViewModel, CategoryManagementClient } from "../autogenerated-clients/api-client";

@Injectable({ providedIn: "root" })
export class CategoryListResolver implements Resolve<Observable<Array<CategoryGridItemViewModel>>> {
  constructor(private categoryClient: CategoryManagementClient) { }

  resolve(routeSnapshot: ActivatedRouteSnapshot) {
    return this.categoryClient
      .getPageOfCategories(new GetPageOfCategoriesQuery({ skip: 0, take: 0, keywords: null, sortKey: null }))
      .pipe(
        map((response: PageOfOfCategoryGridItemViewModel) => {
          return response.items;
        })
      );
  }
}
