import { Injectable } from '@angular/core';
import { ActivatedRouteSnapshot, Resolve } from '@angular/router';
import { Observable } from 'rxjs';
import { GetListOfUsersQuery, UserListItemData, UserManagementClient } from '../autogenerated-clients/api-client';

@Injectable({ providedIn: 'root' })
export class UserListResolver implements Resolve<Observable<Array<UserListItemData>>> {
  constructor(private userManagementClient: UserManagementClient) { }

  resolve(routeSnapshot: ActivatedRouteSnapshot) {
    return this.userManagementClient.getListOfUsers(new GetListOfUsersQuery({  }));
  }
}
