import { Injectable } from "@angular/core";
import { FullRoomHierarchyAreaData } from "../../core/autogenerated-clients/api-client";
import { BehaviorSubject, Observable } from "rxjs";

@Injectable({ providedIn: 'root' })
export class AreasService {
  _areas: BehaviorSubject<Array<FullRoomHierarchyAreaData>> = new BehaviorSubject<Array<FullRoomHierarchyAreaData>>([]);
  areas: Observable<Array<FullRoomHierarchyAreaData>>;

  constructor() {
    this.areas = this._areas.asObservable();
  }

  public setAreas(areas: Array<FullRoomHierarchyAreaData>): void {
    this._areas.next([...areas]);
  }

  public addAreas(areas: Array<FullRoomHierarchyAreaData>): void {
    this._areas.next([...this._areas.value, ...areas]);
  }

  public addArea(area: FullRoomHierarchyAreaData): void {
    this._areas.next([...this._areas.value, area]);
  }
}
