import { ChangeDetectionStrategy, Component, EventEmitter, Input, OnInit, Output, SimpleChanges } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { BehaviorSubject, Subscription } from 'rxjs';
import {
  ExperienceCategoryGridItemViewModel,
  ExperienceDetailsViewModel,
  ExperienceManagementClient,
  ExperienceCategoryManagementClient,
  ExperienceCompensationManagementClient,
  ExtendedWhereData,
  HotelItemData,
  InsertExperienceCommand,
  TaskWhereData,
  GetListOfExperienceCategoriesQuery,
  GetPageOfExperienceCategoriesQuery,
  GetListExperienceCompensationsQuery,
  UpdateExperienceCommand,
  ExperienceTicketStatus,
  ExperienceClientRelationStatus,
  ExperienceResolutionStatus,
} from 'src/app/core/autogenerated-clients/api-client';
import { HotelService } from '../../core/services/hotel.service';
import {Observable} from 'rxjs';
import {map, startWith} from 'rxjs/operators';
import { Select2OptionData } from 'ng-select2';
import { CurrencyPipe } from '@angular/common';
import moment from 'moment';
@Component({
  selector: 'app-add-edit-experience',
  templateUrl: './add-edit-experience.component.html',
  styleUrls: ['./add-edit-experience.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AddEditExperienceComponent implements OnInit {

  @Input() item: ExperienceDetailsViewModel;
  @Input() allWheres: Array<TaskWhereData> = [];
  @Input() allCategories: Array<ExperienceCategoryGridItemViewModel> = [];
  @Output() reloadList: EventEmitter<boolean> = new EventEmitter<boolean>();
  @Output() cancelled: EventEmitter<boolean> = new EventEmitter<boolean>();

  myControl = new FormControl();
  options: string[] = ['NAME1', 'NAME2', 'NAME3', 'NAME4', 'NAME5'];
  filteredOptions: Observable<string[]>;

  public experienceCategory: Array<Select2OptionData>;
  public compensation: Array<Select2OptionData>;

  experienceForm: FormGroup;

  categoriesList: BehaviorSubject<any[]> = new BehaviorSubject<any[]>(null);
  compensationList: BehaviorSubject<any[]> = new BehaviorSubject<any[]>(null);

  experienceTicketStatuses: Array<{ key: ExperienceTicketStatus, value: string }> = [];
  experienceClientRelationStatuses: Array<{ key: ExperienceClientRelationStatus, value: string }> = [];
  experienceResolutionStatuses: Array<{ key: ExperienceResolutionStatus, value: string }> = [];

  statusChange$: Subscription;
  statusFlag: number;

  isexperienceTicketStatus: boolean;
  isexperienceClientRelationStatus: boolean;
  isexperienceResolutionStatus: boolean;

  hotels: HotelItemData[] = [];

  public isCreateNew = true;
  constructor(
    private formBuilder: FormBuilder,
    private toastr: ToastrService,
    private _route: ActivatedRoute,
    private experienceClient: ExperienceManagementClient,
    private experienceCategoryClient: ExperienceCategoryManagementClient,
    private experienceCompensationClient: ExperienceCompensationManagementClient,
    public hotelService: HotelService,
    private currencyPipe: CurrencyPipe
  ) {

    this.experienceTicketStatuses.push({ key: ExperienceTicketStatus.Pending, value: "Pending" });

    this.experienceClientRelationStatuses.push({ key: ExperienceClientRelationStatus.NoClientAction, value: "No client action" });
    this.experienceClientRelationStatuses.push({ key: ExperienceClientRelationStatus.MeetWithClient, value: "Meet with client" });
    this.experienceClientRelationStatuses.push({ key: ExperienceClientRelationStatus.MeetWithClientAtCO, value: "Meet with Client at C/O(avecArchiveiuto)" });

    this.experienceResolutionStatuses.push({ key: ExperienceResolutionStatus.None, value: "None" });
    this.experienceResolutionStatuses.push({ key: ExperienceResolutionStatus.Resolved, value: "Resolved" });
    this.experienceResolutionStatuses.push({ key: ExperienceResolutionStatus.Closed, value: "Closed" });

    this.hotels = hotelService.getHotels();
  }


  ngOnInit(): void {

    this.experienceCategoryClient.getPageOfExperienceCategories(new GetPageOfExperienceCategoriesQuery({ skip: 0, take: 2000 })).subscribe(response => {
      this.experienceCategoryClient.getList(new GetListOfExperienceCategoriesQuery({name : ""})).subscribe(data => {
        this.experienceCategory = [];
        data?.map(parent => {
          var children = [];
          response.items?.map(category => {
            if (category.name == parent.name) {
              children.push({id: category.id, text: parent.name + " - " + category.experienceName})
            }
          })
          this.experienceCategory.push({
            id: "0",
            text: parent.name,
            children: children
          })
        })

        this.categoriesList.next(this.experienceCategory);
      })
    })

    console.log(this.categoriesList);

    this.experienceCompensationClient.getList(new GetListExperienceCompensationsQuery({take:0, skip: 0})).subscribe(response => {
      this.compensation = [];
      response.items?.map(compensation => {
        this.compensation.push({
          id: compensation.id,
          text: compensation.name + " - " + this.currencyPipe.transform(compensation.price, compensation.currency)
        })
      })
      this.compensationList.next(this.compensation)
    })

    console.log(this.compensationList);

    this.filteredOptions = this.myControl.valueChanges.pipe(
      startWith(''),
      map(value => this._filter(value)),
    );

    this.allWheres = this._route.snapshot.data.allWheres;
    this.allCategories = this._route.snapshot.data.allCategories;
    this.initForm();

  }

  private _filter(value: string): string[] {
    const filterValue = value.toLowerCase();

    return this.options.filter(option => option.toLowerCase().includes(filterValue));
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (this.item.id) {
      this.isCreateNew = false;

    } else {
      this.isCreateNew = true;
    }

    if (!changes.item.firstChange) {
      this.setFormData();
    }
  }

  experienceTicketStatusSelectChanged() {
    this.isexperienceTicketStatus = true;
    this.isexperienceClientRelationStatus = false;
    this.isexperienceResolutionStatus = false;
  }

  experienceClientRelationStatusSelectChanged() {
    this.isexperienceTicketStatus = true;
    this.isexperienceClientRelationStatus = true;
    this.isexperienceResolutionStatus = false;
  }

  experienceResolutionStatusSelectChanged(value:any) {
    if ( value == this.experienceResolutionStatuses[0].key) {
      this.isexperienceTicketStatus = true;
      this.isexperienceClientRelationStatus = true;
      this.isexperienceResolutionStatus = false;
    }else {
      this.isexperienceTicketStatus = true;
      this.isexperienceClientRelationStatus = true;
      this.isexperienceResolutionStatus = true;
    }
  }

  initForm() {

    this.isexperienceTicketStatus= true;
    this.isexperienceClientRelationStatus= true;
    
    this.experienceForm = this.formBuilder.group({
      hotelId: [this.item.id],
      guestName: [this.item.guestName],
      roomName: [this.item.roomName],
      checkIn: [this.item.checkIn?.format('yyyy-MM-DD')] ,
      checkOut: [this.item.checkOut?.format('yyyy-MM-DD')],
      reservationId: [this.item.reservationId],
      vip: [this.item.vip],
      experienceEmail: [this.item.email],
      experiencePhoneNumber: [this.item.phoneNumber],
      experienceType: [this.item.type],
      experienceCategory: [this.item.experienceCategoryId],
      actions: [this.item.actions],
      internalFollowUp: [this.item.internalFollowUp],
      compensationName: [this.item.experienceCompensationId],
      description: [this.item.description],
      experienceTicketStatus: [this.item.experienceTicketStatus],
      experienceClientRelationStatus: [this.item.experienceClientRelationStatus],
      experienceResolutionStatus: [this.item.experienceResolutionStatus],
      group: [this.item.group]
    });

  }

  setFormData() {
    this.isexperienceTicketStatus = true;
    this.isexperienceClientRelationStatus = true;

    this.experienceForm.controls.guestName.setValue(this.item.guestName);
    this.experienceForm.controls.roomName.setValue(this.item.roomName);
    this.experienceForm.controls.checkIn.setValue(this.item.checkIn?.format('yyyy-MM-DD'));
    this.experienceForm.controls.checkOut.setValue(this.item.checkOut?.format('yyyy-MM-DD'));
    this.experienceForm.controls.reservationId.setValue(this.item.reservationId);
    this.experienceForm.controls.vip.setValue(this.item.vip);
    this.experienceForm.controls.experienceEmail.setValue(this.item.email);
    this.experienceForm.controls.experiencePhoneNumber.setValue(this.item.phoneNumber);
    this.experienceForm.controls.description.setValue(this.item.description);
    this.experienceForm.controls.actions.setValue(this.item.actions);
    this.experienceForm.controls.internalFollowUp.setValue(this.item.internalFollowUp);
    this.experienceForm.controls.compensationName.setValue(this.item.experienceCompensationId);
    this.experienceForm.controls.experienceCategory.setValue(this.item.experienceCategoryId);
    this.experienceForm.controls.experienceType.setValue(this.item.type);
    this.experienceForm.controls.experienceTicketStatus.setValue(this.item.experienceTicketStatus);
    this.experienceForm.controls.experienceClientRelationStatus.setValue(this.item.experienceClientRelationStatus);
    this.experienceForm.controls.experienceResolutionStatus.setValue(this.item.experienceResolutionStatus);
    this.experienceForm.controls.group.setValue(this.item.group);
  }

  get f() {
    return this.experienceForm.controls;
  }

  save() {
    this.experienceForm.markAsTouched({ onlySelf: false });
    if (this.experienceForm?.invalid) {
      this.toastr.error("You have to fix invalid form fields before you can continue.");
      return;
    }

    let formValues = this.experienceForm.getRawValue();

    let insertRequest = new InsertExperienceCommand({
      guestName: formValues.guestName,
      roomName: formValues.roomName,
      checkIn: moment.utc(formValues.checkIn),
      checkOut: moment.utc(formValues.checkOut),
      reservationId: formValues.reservationId,
      vip: formValues.vip,
      email: formValues.experienceEmail,
      phoneNumber: formValues.experiencePhoneNumber,
      type: formValues.experienceType,
      experienceCategoryId: formValues.experienceCategory,
      actions: formValues.actions,
      internalFollowUp: formValues.internalFollowUp,
      experienceCompensationId: formValues.compensationName,
      description: formValues.description,
      group: formValues.group,
      experienceTicketStatus: formValues.experienceTicketStatus,
      experienceClientRelationStatus: formValues.experienceClientRelationStatus,
      experienceResolutionStatus: formValues.experienceResolutionStatus
    });

    console.log(insertRequest);

    if (this.item.id === null) {

      this.experienceClient.insertExperience(insertRequest).subscribe(
        response => {
          if (response.isSuccess) {
            this.toastr.success(response.message);
            this.reloadList.next(true);
          } else {
            this.toastr.error(response.message);
          }
        },
        error => {
          this.toastr.error(error);
        }
      );
    } else {
      let updateRequest = null;
      updateRequest = new UpdateExperienceCommand({
        id: this.item.id,
        ...insertRequest
      });
      this.experienceClient.updateExperience(updateRequest).subscribe(
        response => {
          if (response.isSuccess) {
            this.toastr.success(response.message);
            this.reloadList.next(true);
          } else {
            this.toastr.error(response.message);
          }
        },
        error => {
          this.toastr.error(error);
        }
      );
    }

  }


  cancel() {
    this.cancelled.next(true);
  }

  public canShowErrorMessage(control: string,): boolean {
    const experienceForm = this.experienceForm as FormGroup;
    if (experienceForm.controls[control]) {
      return !!(
        (experienceForm.controls[control].touched || experienceForm.touched) &&
        experienceForm.controls[control].errors
      );
    } else {
      return false;
    }
  }

  getSelection(data: ExtendedWhereData) {
  }

  ngOnDestroy(): void {
    if (this.statusChange$) this.statusChange$.unsubscribe();
  }

}
