using System;
using System.Collections;
using System.Collections.Generic;

namespace Planner.Domain.Entities
{
	public class Room : BaseEntity
	{
		public Guid Id { get; set; }

		/// <summary>
		/// Room's external ID.
		/// External id is a PMSRoomName from the RC Reservation
		/// </summary>
		public string ExternalId { get; set; }
		public string Name { get; set; }
		
		/// <summary>
		/// Room type. Basic room types are HOTEL, HOSTEL, APPARTMENT. All room types are described in the RoomTypeEnum.
		/// </summary>
		public string TypeKey { get; set; }

		/// <summary>
		/// All rooms have a specific editable order. Order is used in the cleaning plans to optimize the path.
		/// </summary>
		public int OrdinalNumber { get; set; }

		/// <summary>
		/// Name of the floor section. Large floors are divided into sections and subsections.
		/// </summary>
		public string FloorSectionName { get; set; }

		/// <summary>
		/// Name of the floor subsection. Large floors are divided into sections and subsections.
		/// </summary>
		public string FloorSubSectionName { get; set; }

		public Guid? AreaId { get; set; }
		public Area Area { get; set; }

		public Guid? BuildingId { get; set; }
		public Building Building { get; set; }

		public Guid? FloorId { get; set; }
		public Floor Floor { get; set; }

		public IEnumerable<RoomAssetModel> RoomAssetModels { get; set; }
		//public IEnumerable<RoomAsset> RoomAssets { get; set; }

		/// <summary>
		/// Room category ID. Categories are user defined.
		/// </summary>
		public Guid? CategoryId { get; set; }
		/// <summary>
		/// Room category. Categories are user defined.
		/// </summary>
		public RoomCategory Category { get; set; }

		/// <summary>
		/// Some rooms are autogenerated on the reservation synchronization. This flag indicates if the autogeneration process was the creator.
		/// </summary>
		public bool? IsAutogeneratedFromReservationSync { get; set; }

		//public string OccupiedByReservationId { get; set; }
		//public Reservation OccupiedByReservation { get; set; }

		public IEnumerable<Reservation> Reservations { get; set; }

		public bool IsOccupied { get; set; }
		public bool IsClean { get; set; }
		public bool IsOutOfOrder { get; set; }
		public bool IsOutOfService { get; set; }
		public bool IsDoNotDisturb { get; set; }
		public bool IsCleaningInProgress { get; set; }
		public bool IsInspected { get; set; }
		public bool IsGuestCurrentlyIn { get; set; }
		public bool IsCleaningPriority { get; set; }

		public IEnumerable<RoomAssetUsage> AssetUsages { get; set; }

		public IEnumerable<RoomNote> RoomNotes { get; set; }


		public IEnumerable<RoomHistoryEvent> RoomHistoryEvents { get; set; }
		public IEnumerable<CleaningHistoryEvent> CleaningHistoryEvents { get; set; }

		public IEnumerable<RoomBed> RoomBeds { get; set; }
		public IEnumerable<Cleaning> Cleanings { get; set; }

		public Common.Enums.RccHousekeepingStatusCode? RccHousekeepingStatus { get; set; }
		public Common.Enums.RccRoomStatusCode? RccRoomStatus { get; set; }
	}

	public class RoomWithHotelStructureView: Room
	{
		public string AreaName { get; set; }
		public string BuildingName { get; set; }
		public string HotelName { get; set; }
		public string FloorName { get; set; }
		public int FloorNumber { get; set; }
		public string CategoryName { get; set; }
	}

	public class RoomBedWithHotelStructureView: RoomWithHotelStructureView
	{
		public Guid RoomId { get; set; }
		public Room Room { get; set; }

		private IEnumerable<RoomBed> RoomBeds { get; set; }
	}
}
