using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Planner.Persistence.Migrations
{
    public partial class AddedRoomBedTableExtendedHotelSettings : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            //migrationBuilder.AddColumn<bool>(
            //    name: "clean_hostel_room_beds_in_groups",
            //    table: "settings",
            //    type: "boolean",
            //    nullable: false,
            //    defaultValue: false);

            migrationBuilder.AddColumn<bool>(name: "clean_hostel_room_beds_in_groups", table: "settings", nullable: true);
            migrationBuilder.Sql("UPDATE public.settings SET clean_hostel_room_beds_in_groups = false;");
            migrationBuilder.AlterColumn<bool>(name: "clean_hostel_room_beds_in_groups", table: "settings", nullable: false);

            migrationBuilder.CreateTable(
                name: "room_bed",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    room_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "text", nullable: false),
                    is_autogenerated_from_reservation_sync = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_room_bed", x => x.id);
                    table.ForeignKey(
                        name: "fk_room_bed_rooms_room_id",
                        column: x => x.room_id,
                        principalTable: "rooms",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_room_bed_room_id",
                table: "room_bed",
                column: "room_id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "room_bed");

            migrationBuilder.DropColumn(
                name: "clean_hostel_room_beds_in_groups",
                table: "settings");
        }
    }
}
