import { Component, Input, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { EnumData } from '../../core/autogenerated-clients/api-client';

@Component({
  selector: 'app-task-recurring-daily',
  templateUrl: './task-recurring-daily.component.html',
  styleUrls: ['./task-recurring-daily.component.scss']
})
export class TaskRecurringDailyComponent implements OnInit {
  @Input() taskRecurringDailyForm: FormGroup;

  constructor() {
  }

  ngOnInit(): void {
  }
}
