import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { BehaviorSubject } from 'rxjs';
import { DeliveryStatus, FoundStatus, GetLostAndFoundListQuery, GuestStatus, LostAndFoundClient, LostAndFoundListItem, LostAndFoundModel, OtherStatus, TypeOfLoss } from '../core/autogenerated-clients/api-client';
import * as moment from 'moment';
import { LoadingService } from '../core/services/loading.service';
import { ToastrService } from 'ngx-toastr';
import {  HotelItemData,} from 'src/app/core/autogenerated-clients/api-client';
import { HotelService } from '../core/services/hotel.service';

@Component({
  selector: 'app-experience',
  templateUrl: './experience.component.html',
  styleUrls: ['./experience.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ExperienceComponent implements OnInit {

  filterForm: FormGroup;
  itemsList: BehaviorSubject<LostAndFoundListItem[]> = new BehaviorSubject<LostAndFoundListItem[]>(null);
  selectedItem: BehaviorSubject<LostAndFoundModel> = new BehaviorSubject<LostAndFoundModel>(null);
  areDetailsDisplayed$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);

  loadedNumber$: BehaviorSubject<number> = new BehaviorSubject<number>(0);
  totalNumber$: BehaviorSubject<number> = new BehaviorSubject<number>(0);
  showLoadMore$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
  hotels: HotelItemData[] = [];
  pendingNum: number;
  unclaimedNum: number;
  guestNum: number;
  gueNum: number;
  returnedNum: number;
  canceledNum: number;

  public foundStatuses: any;
  public guestStatuses: any;
  public deliveryStatuses: any;
  public otherStatuses: any;

  foundStatusMappings: { [index: number]: string } = {};
  guestStatusMappings: { [index: number]: string } = {};
  deliveryStatusMappings: { [index: number]: string } = {};
  otherStatusMappings: { [index: number]: string } = {};

  constructor(
    private formBuilder: FormBuilder,
    public loading: LoadingService,
    private lostAndFoundClient: LostAndFoundClient,
    private toastr: ToastrService,    
    public hotelService: HotelService,  
    ) {     
      this.hotels = hotelService.getHotels();  
    }

  ngOnInit(): void {

    this.filterForm = this.formBuilder.group({
      keywords: [''],
      dateFrom: [''],
      dateTo: [''],
      hotelId: [],
    });

    this.filterForm.controls.hotelId.setValue(this.hotels[0].id);

    this.filterForm.valueChanges.subscribe(
      value => {
        this.reloadList(true);
      }
    );

    this.reloadList(true);

    this.foundStatusMappings = {};
    this.foundStatusMappings[FoundStatus.WaitingRoomMaid] = "Waiting Room Maid";
    this.foundStatusMappings[FoundStatus.Received] = "Received";
    this.foundStatuses = FoundStatus;

    this.guestStatusMappings = {};
    this.guestStatusMappings[GuestStatus.Unclaimed] = "Unclaimed";
    this.guestStatusMappings[GuestStatus.ClientContactedByEmail] = "Client Contacted By Email";
    this.guestStatusMappings[GuestStatus.ClientContactedByPhone] = "Client Contacted By Phone";
    this.guestStatusMappings[GuestStatus.ClientUndecided] = "Client Undecided";
    this.guestStatusMappings[GuestStatus.WaitingForClientReturn] = "Waiting For Client Return";
    this.guestStatuses = GuestStatus;
    
    this.deliveryStatusMappings = {};
    this.deliveryStatusMappings[DeliveryStatus.None] = "None";
    this.deliveryStatusMappings[DeliveryStatus.WaitingForShipment] = "Waiting For Shipment";
    this.deliveryStatusMappings[DeliveryStatus.WaitingForHandDelivered] = "Waiting For Hand Delivered";
    this.deliveryStatusMappings[DeliveryStatus.OTShipped] = "OT Shipped";
    this.deliveryStatusMappings[DeliveryStatus.HandDelivered] = "Hand Delivered";
    this.deliveryStatuses = DeliveryStatus;

    this.otherStatusMappings = {};
    this.otherStatusMappings[OtherStatus.None] = "None";
    this.otherStatusMappings[OtherStatus.Expired] = "Expired";
    this.otherStatusMappings[OtherStatus.RefusedByTheClient] = "Refused By The Client";
    this.otherStatusMappings[OtherStatus.BadReferencing] = "Bad Referencing";
    this.otherStatusMappings[OtherStatus.Destroy] = "Détruit";
    this.otherStatusMappings[OtherStatus.ReturnedToInventor] = "Rendu à l’inventeur";
    this.otherStatusMappings[OtherStatus.GivenToAnotherPerson] = "Donné à une autre personne";
    this.otherStatusMappings[OtherStatus.DisappearedOrLost] = "Disparu/Perdu";
    this.otherStatuses = OtherStatus;
  }

  createNewFound() {
    const item = new LostAndFoundModel({
      id: null,
      lostOn: moment(),
      foundStatus: FoundStatus.WaitingRoomMaid,
      guestStatus: GuestStatus.Unclaimed,
      deliveryStatus: DeliveryStatus.None,
      otherStatus: OtherStatus.None,
      typeOfLoss: TypeOfLoss.Customer,
      address: '',
      name: '',
      phoneNumber: '',
      referenceNumber: '',
      description: '',
      roomId: null,
      reservationId: null,
      hotelId: this.filterForm.getRawValue().hotelId,
    });
    this.selectedItem.next(item);
    this.areDetailsDisplayed$.next(false);
    this.areDetailsDisplayed$.next(true);
  }

  // columnFilter(val: any){
  //   console.log(val);
  //   this.loading.start();
  // }

  
  reloadList(reload: boolean) {
    if (reload) {
      this.loadedNumber$.next(0);
    }

    this.areDetailsDisplayed$.next(false);

    this.loading.start();
    this.lostAndFoundClient.getList(new GetLostAndFoundListQuery({
      skip: this.loadedNumber$.value,
      take: 20,
      dateFrom: this.filterForm.controls.dateFrom.value,
      dateTo: this.filterForm.controls.dateTo.value,
      keyword: this.filterForm.controls.keywords.value,
      loadFoundItems: true,
      loadLostItems: false,
    })).subscribe((response) => {
      if (response.isSuccess) {
        this.itemsList.next(response.data.items);
        this.totalNumber$.next(response.data.totalNumberOfItems);
        this.loadedNumber$.next(this.loadedNumber$.value + 20);
        this.showLoadMore$.next(this.loadedNumber$.value < this.totalNumber$.value);
        this.pendingNum = 0;
        this.unclaimedNum = 0;
        this.gueNum = 0;
        this.returnedNum = 0;
        this.canceledNum = 0;
        for (let i = 0; i < this.itemsList.value.length; i++) {
          console.log(this.itemsList.value[i])
          if (this.itemsList.value[i].foundStatus == 0) {
            this.pendingNum += 1;
          }
        }
        for (let i = 0; i < this.itemsList.value.length; i++) {
          if (this.itemsList.value[i].guestStatus == 0) {
            this.unclaimedNum += 1;
          }
        }
        for (let i = 0; i < this.itemsList.value.length; i++) {
          if (this.itemsList.value[i].foundStatus == 0 && this.itemsList.value[i].guestStatus == 0 && this.itemsList.value[i].deliveryStatus != 1 && this.itemsList.value[i].deliveryStatus != 2) {
            this.gueNum += 1;
          }
        }
        console.log(this.gueNum);
        this.guestNum = this.itemsList.value.length - this.gueNum;
        for (let i = 0; i < this.itemsList.value.length; i++) {
          if (this.itemsList.value[i].deliveryStatus == 4 || this.itemsList.value[i].deliveryStatus == 3) {
            this.returnedNum += 1;
          }
        }
        for (let i = 0; i < this.itemsList.value.length; i++) {
          if (this.itemsList.value[i].otherStatus != 0) {
            this.canceledNum += 1;
          }
        }

      } else {
        this.toastr.error(response.message);
      }
      this.loading.stop();
    },
      (error) => {
        this.toastr.error(error);
        this.loading.stop();
      });
  }

  selectItem(item: LostAndFoundListItem) {
    this.lostAndFoundClient.getById(item.id).subscribe(
      (response) => {
        if (response.isSuccess) {
          this.selectedItem.next(response.data);
          this.areDetailsDisplayed$.next(true);
        } else {
          this.toastr.error('Error loading item.');
        }
      },
      (error) => {
        this.toastr.error(error);
      }
    );
  }

  onItemEditCancelled() {
    this.areDetailsDisplayed$.next(false);
    this.selectedItem.next(null);
  }

}
